"""empty message

Revision ID: 25df31583d
Revises: 1c72717785c
Create Date: 2015-03-07 09:50:52.957849

"""

# revision identifiers, used by Alembic.
revision = '25df31583d'
down_revision = '1c72717785c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'owner_id')
    op.drop_table('assignment')
    ### end Alembic commands ###
