"""empty message

Revision ID: 2b43cdd81e1
Revises: 25df31583d
Create Date: 2015-03-07 09:57:14.079285

"""

# revision identifiers, used by Alembic.
revision = '2b43cdd81e1'
down_revision = '25df31583d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
