"""empty message

Revision ID: 2f736eaa3d9
Revises: 50b2e8d21e6
Create Date: 2015-03-07 16:22:45.927874

"""

# revision identifiers, used by Alembic.
revision = '2f736eaa3d9'
down_revision = '50b2e8d21e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assigned_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_owner_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_assigned_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'task', 'user', ['assigned_id'], ['id'])
    op.drop_column('task', 'owner')
    op.drop_column('task', 'assigned')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assigned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_assigned_fkey', 'task', 'user', ['assigned'], ['id'])
    op.create_foreign_key('task_owner_fkey', 'task', 'user', ['owner'], ['id'])
    op.drop_column('task', 'owner_id')
    op.drop_column('task', 'assigned_id')
    ### end Alembic commands ###
